### PR TITLE
Update Date.js

### PR DESCRIPTION
**Pull request by sunnykumarsingh2050**
Line 1: 'parse'  has been removed

### CODE REVIEW

**Review by shubhanshu02 — APPROVED** [review]
Looks good to me! @sunnykumarsingh2050, there are two more variables to be removed as a part of #71 if you'd like to do with this PR. Otherwise, we can merge this

**Comment by sunnykumarsingh2050** [comment]
> Looks good to me! @sunnykumarsingh2050, there are two more variables to be removed as a part of #71 if you'd like to do with this PR. Otherwise, we can merge this

ok I will do it.

**Review by shubhanshu02 — CHANGES_REQUESTED** [review]
Run `npm run format` on the repository to format the files. Rest everything is fine.

**Comment by shubhanshu02** [comment]
Closing since the issue already closed. Thanks.

**Pull request closed without merging**
