### PR TITLE
Fixed issue with 'view more' and 'see more' buttons

### PR DESCRIPTION
**Pull request by aayushsrivastava9760**
**Fixes**

The non-responsiveness of 'view more' and 'see more' buttons while hovering, as stated in #151

**Description**

Have made changes in `pages/index.tsx` for 'view more' buttons and `components/HackathonCard/HackathonCard.tsx` for 'see more' buttons . The buttons now have hovering effects . 

view more

see more

**Checklist:**

-   [x] I have read the contribution guidelines in the repository.
-   [x] My branch is up-to-date with upstream branch.
-   [x] My pull request has a descriptive title (not a vague title like "Update package.json").
-   [x] My code follows the established code style of the repository.
-   [x] I have tried running the project locally and verified that there are no visible errors.

### CODE REVIEW

**Comment by shubhanshu02** [comment]
> @shubhanshu02 bhaiya, my PR is showing this :- WhatsApp Image 2021-10-16 at 08 51 37 WhatsApp Image 2021-10-16 at 09 07 45
> 
> I think the issue is arising because of the 'merging concluded' commit in which I used `git pull upstream main` and not with the button fixes. The site is working fine locally. How should I tackle it bhaiya?

As you can read on the CodeClimate page, it shows that the same piece of code is being repeated. Click on "Read Up" beside each issue to read more on that issue. That's probably because the issue was present before this PR, but since we installed CodeClimate a few days back and this PR changes that particular file, the issue got caught.

You need to refactor the code in those parts to use only one of those parts - say you enclosed those in a single component and rendered that component with current children. This is for better maintainability of the code in the future.

**Comment by shubhanshu02** [comment]
> So @shubhanshu02 bhaiya will it be alright if I make a component under `/components/Header/` named `Subheader.tsx`.

This repeated code is present on the Home page (`/pages/index.tsx`). Placing it inside the Header component's folder doesn't seem right. How about a new folder `/components/Home/` and then shift this part there? 

The filename can be anything relevant (like `EventHeader.tsx` etc, that's your choice)

**Comment by aayushsrivastava9760** [comment]
Understood @shubhanshu02  bhaiya , I am on it .

**Comment by aayushsrivastava9760** [comment]
@shubhanshu02  bhaiya , the code below is being repeated with different `tag` and text,
```
<Text
       tag="h1"
       textSize={{ xs: "title", md: "display1" }}
       textColor="#003e54"
       fontFamily="madetommy-bold"
>
Ready to Submit?
</Text>
```
I think a component of this part named `EventText.tsx` should solve the problem .

**Comment by aayushsrivastava9760** [comment]
Understood @shubhanshu02  bhaiya , thank you for the clarification .

**Pull request merged**
