### PR TITLE
Added "noopener noreferrer" as rel attribute in external anchor tags.

### PR DESCRIPTION
**Pull request by ujju20**
I have added "noopener noreferrer" as rel attribute in the external anchor tags of the required files.

### CODE REVIEW

**Review by shubhanshu02 — CHANGES_REQUESTED** [review]
Remove commits other than the one name "Removed Unused variables" and run `npm run format` to format the files.

**Comment by ujju20** [comment]
Can you help me how to do it? like how to remove commit?

**Comment by shubhanshu02** [comment]
> Can you help me how to do it? like how to remove commit?

The easiest way to remove those changes is to use `git revert` as follows. This will create two revert commits though, but that's no problem for now.
```bash
git revert 56a4192b09ac85b833c88a6c010267055682aafc 24869737816310d735da75ce065533f78ee0fd19
```
Here the two strings are the respective commit hashes.

**Comment by ujju20** [comment]
I have removed the commit from this unused branch now I have to what?

**Comment by shubhanshu02** [comment]
Did you push the changes?

**Comment by ujju20** [comment]
yes I have pushed the changes 
Has my PR merged?

**Comment by shubhanshu02** [comment]
No, actually you closed the PR. I cannot see any commits with this PR. 

Maybe you have reset your branch to a commit older than the required commit, so it was also removed?

**Comment by ujju20** [comment]
actually git is saying that my head is detached but head is at latest revert commit.
So what to do now?

**Comment by shubhanshu02** [comment]
So, the head is detached at the latest revert commit?
Can you tell what exactly you did, I mean the commands?

**Comment by ujju20** [comment]
I am doing this again.

**Comment by shubhanshu02** [comment]
Sure, np. You may undo a detach operation by `git switch -`, though.

**Comment by ujju20** [comment]
ok i'll try.

**Pull request closed without merging**
