### PR TITLE
Migrated Dates.js to Date.tsx

### LINKED ISSUE #93: Migrate Frontend Components to TypeScript
Migrate the JavaScript modules to TypeScript. 

### Files

- [x] context/auth.js (#102)
- [x] components/Header/Header.js (#122)
- [x] components/HackathonCard/HackathonCard.js (#115)
- [x] components/Sorry/Sorry.js (#103)
- [x] components/Footer/Footer.js  (#104)
- [x] components/Date/Date.js (#112)
- [x] components/Cards/Card.js (#108)
- [x] components/Buttons/IconsButton.js (#120)
- [x] components/Clipboard/Clipboard.js (#125)
- [x] components/Profile/index.js (#111)
- [x] components/Profile/Interests.js (#107 )
- [x] components/Profile/ProfileTabs.js (#103)
- [x] components/Profile/EditProfileModal.js (#113)
- [X] components/Profile/TeamCard.js (Fixed by #94)
- [x] components/Profile/SkillOptions.js (#126)
- [x] util/constants.js (#103)
- [x] util/axios.js (#103)
- [x] pages/index.js (#124 )
- [x] pages/submission/[id].js (#102)
- [x] pages/hackathons.js (#114)
- [x] pages/_app.js (#110)
- [x] pages/profile/[username].js (#117)
- [x] pages/hackathon/[slug]/index.js (#123)
- [x] pages/hackathon/[slug]/teams/[team_id]/index.js
- [x] pages/hackathon/[slug]/teams/[team_id]/submit.js (#118)
- [x] pages/hackathon/[slug]/register.js (#116)
- [x] pages/contributors.js (#106)
- [x] pages/_document.js (#109)
- [x] #97

### Steps to follow
1. Rename the file to .tsx or .ts extension as required.
2. Look for the source of props in the component, if required.
3. If the data was obtained from the backend, look for the response type in the backend, using the below list. The response types of each serializer have been added to the `/types/backend.ts`.
4. Migrate to TypeScript.

Backend: https://cops-hackalog.herokuapp.com/
Serializer List and Types for the Backend: https://hackalog-docs.vercel.app/#/serializers

Note: An example of one such migration is in fbbad4c.

### Points to be noted

- Some files only store data and functions, so interfaces are to be made accordingly.
- Add the types to the folder `/types/` to a new file as required. If the same types were already created, prefer reusing them.
- You may need to check the [backend API](https://cops-hackalog.herokuapp.com/) for getting the object types for responses.

### Some Links that may be useful

https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/basic_type_example/
https://www.typescriptlang.org/docs/handbook/intro.html

### PR DESCRIPTION
**Pull request by ankur12-1610**
**Fixes**

Fixes #93 

**Description**

**Checklist:**

-   [x] I have read the contribution guidelines in the repository.
-   [x] My branch is up-to-date with upstream branch.
-   [x] My pull request has a descriptive title (not a vague title like "Update package.json").
-   [x] My code follows the established code style of the repository.
-   [x] I have tried running the project locally and verified that there are no visible errors.

### CODE REVIEW

**Review by shubhanshu02 — CHANGES_REQUESTED** [review]
LGTM. Just run prettier (`npm run format`) and pull the latest changes from this repo.

**Comment by ankur12-1610** [comment]
> LGTM. Just run prettier (`npm run format`) and pull the latest changes from this repo.

Done!

**Review by shubhanshu02 — APPROVED** [review]
Thanks, @ankur12-1610 :clinking_glasses:

**Comment by ankur12-1610** [comment]
> Thanks, @ankur12-1610

Anytime :)

**Pull request merged**
