### PR TITLE
migrated clipboard.js to clipboard.tsx

### PR DESCRIPTION
**Pull request by sahilsaini110**
**Fixes**

Fixes part of #93

**Description**

**Checklist:**

-   [x] I have read the contribution guidelines in the repository.
-   [x] My branch is up-to-date with upstream branch.
-   [x] My pull request has a descriptive title (not a vague title like "Update package.json").
-   [x] My code follows the established code style of the repository.
-   [x] I have tried running the project locally and verified that there are no visible errors.

### CODE REVIEW

**Review by shubhanshu02 — APPROVED** [review]
LGTM. Just can you revert the changes in `package-lock.json`?

**Comment by sahilsaini110** [comment]
> LGTM. Just can you revert the changes in `package-lock.json`?

I have push the new file may you plz check ones.

**Comment by shubhanshu02** [comment]
Format the changes as well using `npm run format`

**Review by shubhanshu02 — APPROVED** [review]
LGTM. Thanks @sahilsaini110 :clinking_glasses:

**Pull request merged**
